apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-manual-upgrade-steps-cluster
  region: ap-southeast-1
  version: "1.19"

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 2
    volumeSize: 80
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key